### ISSUE TITLE
Fix the links so we can subscribe easier

### ISSUE THREAD

**Issue by borg286** [GeorgeSG/sub.rehab#3]
Please see this post on how the links should be formatted
https://kbin.social/m/lemmyworld@lemmy.world/t/56137/Sub-Rehab-See-where-reddit-communities-have-relocated-to#entry-comment-239685

**Comment by GeorgeSG** [comment]
The problem is that everyone would want to have a community link for subscribe on their own instance.

So if you are a `lemmy.world` user and you want to subscribe to a `lemmy.ml` community, you need the link to be https://lemmy.world/c/<community>@lemmy.ml (and vice-versa).
 
So sub.rehab would need to know your home instance to be able to give you a proper link. This is also different between kbin and lemmy (`/m/` vs `/c/`).

One way to do this is to enter your home instance on sub.rehab so it can generate links for you. Kinda like what @moon_matter@kbin.social [suggested here](https://lemmy.world/comment/351050).

Definitely doable though.

**Comment by StephenWetzel** [comment]
Yeah, I would support a simple text box where you enter your home instance and then it personalizes the links for you.  Maybe provide a dropdown with the most common ones in it too?

**Comment by GeorgeSG** [comment]
This is now supported with the experimental Home Instance feature we launched yesterday. Thank you for your suggestions!
